version: '3.9'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    depends_on:
      - wordpress
    networks:
      - lberrada_network
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    expose:
       - "9000"
    volumes:
      - website:/var/www/html
    depends_on:
      - mariadb
    networks:
      - lberrada_network
    restart: always
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - lberrada_network
    restart: always
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

      
networks:
  lberrada_network:

volumes:
  website:
    driver_opts:
      type: none
      device: /home/lberrada/data/website
      o: bind

  mariadb:
    driver_opts:
      type: none
      device: /home/lberrada/data/mariadb
      o: bind
